### ISSUE TITLE
Produce test vectors for `did:dht`

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/web5-spec#11] opened 2023-11-08 23:41 UTC
Produce language agnostic test vectors that can be used by each implementation to ensure that the following features work correctly:
* Creation
* Resolution

It may make sense for these vectors to live alongside the `did:dht` spec in the repo thats in

Related: #17

**Comment by decentralgabe** [comment] 2023-11-09 19:54
related to https://github.com/TBD54566975/did-dht-method/issues/37

**Comment by decentralgabe** [comment] 2023-11-22 01:08
test vectors are available here https://did-dht.com/#test-vectors need to be uptaken by this repo

**Comment by decentralgabe** [comment] 2023-12-21 21:08
@nitro-neal are you able to help uptake the vectors here?

**Comment by andresuribe87** [comment] 2023-12-28 22:42
Just noting that I added some test vectors, and updated the implementation, in https://github.com/TBD54566975/web5-kt/pull/181

**Comment by decentralgabe** [comment] 2024-02-16 17:34
bumping this [after Adam's comment](https://github.com/TBD54566975/web5-swift/pull/15#discussion_r1492556338) that these are out of date with the spec

**Comment by decentralgabe** [comment] 2024-08-16 04:16
closing as a dupe of #167

**Closed by decentralgabe** 2024-08-16 04:16 UTC
Labels: testing, did
