### ISSUE TITLE
Produce test vectors for W3C VC Data Model 1.1

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/web5-spec#24] opened 2023-11-09 07:29 UTC
Produce language agnostic test vectors that can be used by each implementation to ensure that the following features work correctly:
* Creation
* Verification
* Validation - this could just be a JSON schema that can be used in all SDKs

Related: #17

**Comment by decentralgabe** [comment] 2023-11-16 17:24
There are a [set of test vectors in the test suite here](https://github.com/w3c/vc-test-suite/tree/gh-pages/test/vc-data-model-1.0/input). I don't think we need to use all of them.

What I've found to be sufficient is to replicate a few of the [examples in the spec itself](https://www.w3.org/TR/vc-data-model).

**Comment by decentralgabe** [comment] 2024-08-16 04:16
Closing as dupe of #168

**Closed by decentralgabe** 2024-08-16 04:16 UTC
Labels: testing, vc
